djangostart/apps/forms_base/urls.py
from django.conf.urls import  url,include
from  . import views

urlpatterns = [
    url('^$',views.index,name='index'),
    url('^register/$', views.register,name='register'),
    url('^login/$', views.login, name='login'),
    url('^logout/$', views.logout, name='logout'),
]

djangostart/djangostart/urls.py
from django.conf.urls import url
from django.contrib import admin

#导入的根路径是项目的根目录djangostart
from app01 import views
from django.conf.urls import include,url
import debug_toolbar

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #当路由过来，匹配上的时候，会执行视图的指定函数名 -》Django会给视图传递一个参数
    url(r'^demo/$',views.demo ,name='demo'),
    url(r'^demo_form/$',views.demo_form),
    url(r'^demo_form2/$',views.demo_form2),
    url(r'^demo_form2_db/$',views.demo_form2_db),
    url(r'^route_base/',include('apps.route_base.urls',namespace='route_base')),
    url(r'^route_resolve/',include('apps.route_resolve.urls',namespace='route_resolve')),
    url(r'^django_templates/',include('apps.django_templates.urls',namespace='django_templates')),
    url(r'^forms_base/',include('apps.forms_base.urls',namespace='forms_base')),
    url(r'^forms_auth/',include('apps.forms_auth.urls',namespace='forms_auth')),
]

djangostart/apps/forms_base/models.py
from django.db import models

# Create your models here.

from django.db import models
import json
# Create your models here.

class UserInfo(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=18)
    password = models.CharField(verbose_name="密码", max_length=128)

    def __str__(self):
        return self.username

    #自定义方法
    def to_dict(self):
        return dict([(attr, getattr(self, attr)) for attr in [f.name for f in self._meta.fields]])


    #定义元数据  =》显示类
    class Meta:
        verbose_name = "用户列表"
        verbose_name_plural = verbose_name

djangostart/apps/forms_base/forms.py
from  django import forms

#定义一个类===》一个类对应一个表单
class ContactForm(forms.Form):
    #一个属性就是一个表单元素
    #forms.CharFiled  =>字段类型
    #label  =>参数 （
    #widdgets  =>小部件
    """
        label =>设置标题（默认：属性名称）
        min_length =》设置元素的最短长度
        required =>True(默认必填项)
        initial =>初始化的值
        error+messsages  =>设置错误提示信息
    """
    subject = forms.CharField(label="主题",
                              min_length=8,
                              required=True,
                              initial="django_form",
                              error_messages={
                                  "min_legnth":"主题最少为8个字符",
                                  "reqiured":"主题是必填项",
                              }
                              )
    content = forms.CharField(label="正文",widget=forms.Textarea)

    content2 = forms.CharField(label="正文2",
                               widget=forms.Textarea(
                                   attrs={
                                       "class":"clasa",
                                       "name":"content2",
                                       "style":"color:blue;font-size:24px;",
                                       "col":30,

                                   }
                               )
                            )
    sender = forms.EmailField(label="发送人")
    cc_myself = forms.BooleanField(label="抄送")
    password = forms.CharField(label="密码",widget=forms.PasswordInput)
    gender = forms.fields.ChoiceField(
        choices=((1,"男"), (2, "女"), (3, "保密")),
        label="性别",
        initial=3,
        widget=forms.widgets.RadioSelect()
    )
    #下拉选择
    hobby = forms.fields.ChoiceField(
        choices=((1, "篮球"), (2, "足球"), (3, "双色球"),),
        label="爱好",
        initial=3,
        widget=forms.widgets.Select()
    )
    #多选
    hobby2 = forms.fields.MultipleChoiceField(
        choices=((1, "篮球"), (2, "足球"), (3, "双色球"),),
        label="爱好",
        initial=[1,3],
        widget=forms.widgets.SelectMultiple()
    )
    #单选checkbox
    keep = forms.fields.ChoiceField(
        label="是否记住密码",
        initial="checked",
        widget=forms.widgets.CheckboxInput()
    )
    #多选checkbox
    hobby3 = forms.fields.MultipleChoiceField(
        choices=((1, "篮球"), (2, "足球"), (3, "双色球"),),
        label="爱好",
        initial=[1, 3],
        widget=forms.widgets.CheckboxSelectMultiple()
    )


# 通过django.forms定义表单
from django import forms
from . import models


class RegisterForm(forms.ModelForm):
    """注册表单"""
    # 因为Model中的元素默认是会把密码显示出来的，所以在这里重新定义一个password
    password = forms.CharField(label="输入密码", max_length=18, widget=forms.PasswordInput)
    password2 = forms.CharField(label="确认密码", max_length=18, widget=forms.PasswordInput)
    class Meta:
        model = models.UserInfo
        # 将model UserInfo中的字段生成到表单
        # exclude表示排除哪个字段，fields表示包含哪个字段， 两个选项必须选其一
        # exclude = ()  -->表示userInfo里所有的字段都可以用  -->元祖类型
        fields = ('username', 'password')

    def clean_username(self):
        """
        对username字段做检查用户名是否已经被注册
        注意字段一定要有返回值
        """
        # self.cleaned_data["username"] => 获取表单提交的username数据
        users = models.UserInfo.objects.filter(username=self.cleaned_data["username"])
        if not users:
            return self.cleaned_data["username"]
        else:
            raise forms.ValidationError("该用户名已经被使用")

    def clean(self):
        """
        验证两次输入的密码是否一次
        对整个表单验证时，不需要返回值
        """
        if self.cleaned_data.get("password") != self.cleaned_data.get("password2"):
            raise forms.ValidationError("密码不一致！")


class LoginForm(forms.ModelForm):
    """登录表单"""
    password = forms.CharField(label="密码", max_length=30, widget=forms.PasswordInput(attrs={"size": 20, }))

    def clean_username(self):
        user = models.UserInfo.objects.filter(username__iexact=self.cleaned_data["username"])
        if not user:
            raise forms.ValidationError("用户不存在")
        else:
            return self.cleaned_data["username"]

    class Meta:
        model = models.UserInfo
        exclude = ()

djangostart/apps/forms_base/views.py
from django.shortcuts import render
from .forms import ContactForm

# Create your views here.

def index(request):
    #创建了一个Form表单
    form = ContactForm(request.GET)
    print(form)
    return render(request, "forms_base/index.html", {"form":form})

from django.shortcuts import render, HttpResponse,redirect,reverse
from django.contrib.auth.hashers import make_password, check_password
from django.contrib import messages
from .forms import ContactForm, RegisterForm, LoginForm
from .models import UserInfo


def register(request):
    # 没有绑定数据的表单
    reg_form = RegisterForm()
    if request.method == 'POST':
        #绑定数据的表单
        reg_form = RegisterForm(request.POST)
        if reg_form.is_valid():
            # is_valid => 用来验证表单中的所有数据中否都合法
            # 验证用户名：检查用户是否已经在数据中存在，可以对某个字段来验证
            # 给某个字段添加验证方法:定义form的时候，clean_字段名
            # 给整个表单添加验证方法：定义form的时候，加一个clean方法
            username = reg_form.cleaned_data["username"]
            password = reg_form.cleaned_data["password"]
            password = make_password(password)
            UserInfo.objects.create(username=username, password=password)
            print("合法")
            messages.add_message(request,messages.INFO,"注册成功")
            return redirect(reverse("forms_base:login"))
        else:
            print("不合法")
            messages.add_message(request, messages.INFO, "不合法")
    return render(request, 'forms_base/register.html', {"form":reg_form})


def login(request):
    login_form = LoginForm()
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        # is_valid提交的数据合法(会检查所有字段及表单整体的合法性)
        if login_form.is_valid():
            password = login_form.cleaned_data["password"]
            user = UserInfo.objects.get(username=login_form.cleaned_data["username"])
            #user.password =>密文
            #password =>明文
            if check_password(password,user.password):
                print("用户名密码验证成功！")
                # 注意需要把user对象需要能被序列化（json格式）
                request.session['user'] = user.username
                print(request.session["user"])
                # 1. 生成一个随机的sessionid字符串
                # 2. 将sessionid和键值,对保存到本地
                # 3. 通过cookie将sessionid保存到客户端
                # 4. 只可以通过sesssionid来判断当前是哪个用户登录
                return redirect(reverse("forms_base:index"))
            else:
                # 验证失败
                messages.add_message(request, messages.INFO, "用户名密码验证失败")
    return render(request, 'forms_base/login.html', {"form": login_form})


def logout(request):
    print('退出成功')
    return HttpResponse("退出成功")

djangostart/apps/forms_base/templates/forms_base/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>这是原始表单</h1>
<h2>欢迎您.{{ request.session.user }}</h2>
<h2>欢迎您.{{ request.user }}</h2>
<form action="/your-name/" method="post">
	<p><label for="id_subject">Subject:</label>
	    <input id="id_subject" type="text" name="subject" maxlength="100" required /></p>
	<p><label for="id_message">Message:</label>
	    <textarea name="message" id="id_message" required></textarea></p>
	<p><label for="id_sender">Sender:</label>
	    <input type="email" name="sender" id="id_sender" required /></p>
	<p><label for="id_cc_myself">Cc myself:</label>
	    <input type="checkbox" name="cc_myself" id="id_cc_myself" /></p>
</form>
<form>
   {{ form.as_table}}
    <button type="submit">提交</button>
</form>


<h1>django-form表单-as_table</h1>
{{ form.as_table }}
<h1>django-form表单-as_p</h1>
{{ form.as_p }}
<h1>django-form表单-as_ul</h1>
{{ form.as_ul }}
<h1>django-form表单-单个元素</h1>
{{ form.subject.label }}:{{ form.subject }}
</body>
</html>

djangostart/apps/forms_base/templates/forms_base/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>欢迎你！</h1>
{% if messages %}
    {% for item in messages %}
        {{ item }}-----
    {% endfor %}
{% endif %}
<ul>
    <li><a href="{% url 'forms_base:register' %}">注册</a></li>
    <li><a href="{% url 'forms_base:login' %}">登录</a></li>
    <li><a href="{% url 'forms_base:logout' %}">注销</a></li>
    <li><a href="{% url 'forms_base:index' %}">首页</a></li>
</ul>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="登录">
</form>
</body>
</html>

djangostart/apps/forms_base/templates/forms_base/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

djangostart/apps/forms_base/templates/forms_base/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>欢迎你！</h1>
{% if messages %}
    {% for item in messages %}
        {{ item }}-----
    {% endfor %}
{% endif %}
<ul>
    <li><a href="{% url 'forms_base:register' %}">注册</a></li>
    <li><a href="{% url 'forms_base:login' %}">登录</a></li>
    <li><a href="{% url 'forms_base:logout' %}">注销</a></li>
    <li><a href="{% url 'forms_base:index' %}">首页</a></li>
</ul>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="注册">
</form>
</body>
</html>