djangostart/apps/forms_auth/urls.py
from django.conf.urls import  url,include
from  . import views

urlpatterns = [
    url('^$',views.index,{"template_name":"forms_auth/index.html"},name='index'),
    url('^register/$', views.register,name='register'),
    url('^login/$', views.login, name='login'),
    url('^logout/$', views.logout, name='logout'),
]

djangostart/djangostart/urls.py
from django.conf.urls import url
from django.contrib import admin

#导入的根路径是项目的根目录djangostart
from app01 import views
from django.conf.urls import include,url
import debug_toolbar

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #当路由过来，匹配上的时候，会执行视图的指定函数名 -》Django会给视图传递一个参数
    url(r'^demo/$',views.demo ,name='demo'),
    url(r'^demo_form/$',views.demo_form),
    url(r'^demo_form2/$',views.demo_form2),
    url(r'^demo_form2_db/$',views.demo_form2_db),
    url(r'^route_base/',include('apps.route_base.urls',namespace='route_base')),
    url(r'^route_resolve/',include('apps.route_resolve.urls',namespace='route_resolve')),
    url(r'^django_templates/',include('apps.django_templates.urls',namespace='django_templates')),
    url(r'^forms_base/',include('apps.forms_base.urls',namespace='forms_base')),
    url(r'^forms_auth/',include('apps.forms_auth.urls',namespace='forms_auth')),
]

djangostart/apps/forms_auth/models.py
from django.db import models

# Create your models here.

djangostart/apps/forms_auth/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.Form):
    """注册表单"""
    username = forms.CharField(label="用户名", max_length=30, widget=forms.TextInput(attrs={"size":20,}))
    email = forms.EmailField(label="邮 箱", max_length=30, widget=forms.TextInput(attrs={"size":20,}))
    password1 = forms.CharField(label="密码1", max_length=30, widget=forms.PasswordInput(attrs={"size":20,}))
    password2 = forms.CharField(label="密码2", max_length=30, widget=forms.PasswordInput(attrs={"size":20,}))

    def clean_username(self):
        '''验证重复昵称，需要返回字段值'''
        users = User.objects.filter(username__iexact=self.cleaned_data["username"])
        if not users:
            return self.cleaned_data["username"]
        raise forms.ValidationError("该昵称已被占用，请使用其他的昵称")

    def clean_email(self):
        '''验证重复email，需要返回字段值'''
        emails = User.objects.filter(email__iexact=self.cleaned_data["email"])
        if not emails:
            return self.cleaned_data["email"]
        raise forms.ValidationError("该邮箱已经被使用请使用其他的")

    def clean(self):
        """
        验证两次输入的密码是否一致
        不需要自己返回数据
        """
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        print(password2, password1)
        if password1 != password2:
            raise forms.ValidationError("两次输入的密码不一致")


class LoginForm(forms.Form):
    """登录表单"""
    username = forms.CharField(label="用户名", max_length=30, widget=forms.TextInput(attrs={"size": 20, }))
    password = forms.CharField(label="密  码", max_length=30, widget=forms.PasswordInput(attrs={"size": 20, }))

djangostart/apps/forms_auth/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from .forms import LoginForm, RegisterForm

def index(request,template_name):
    return render(request,template_name)

#登录函数，使用auth
def _login(request,username,password):
    ret = True
    # authenticate: 认证成功=> 返回用户, 认证失败=>None
    user  = authenticate(username=username,password=password)
    if user:
        #用户可用状态
        if user.is_active:
            #登录
            auth_login(request,user)
        else:
            print("用户不可用")
            messages.add_message(request,messages.INFO,"用户不可用")
            ret =  False
    else:
        print("用户认证失败")
        messages.add_message(request,messages.INFO,"用户认证失败")
        ret = False
    return ret

def login(request):
    # 提交:POST
    # 直接访问:GET
    print(request.method)
    # form表单实例化:空的表单
    form = LoginForm()
    if request.method == "POST":
        # check data
        # 表单数据绑定
        form = LoginForm(request.POST)
        # is_valid: 验证表单数据是否合法(合法返回True)
        if form.is_valid():
            ret = _login(request, form.cleaned_data["username"], form.cleaned_data["password"])
            if ret :
                return redirect(reverse("forms_auth:index"))
    return  render(request,"forms_auth/login.html",{"form":form})

def register(request):
    form = RegisterForm()
    if request.method =="POST":
        # 将数据绑定到RegisterForm表单
        form = RegisterForm(request.POST)
        # is_valid: 验证表单数据是否合法(合法返回True)
        # 用户名唯一、邮箱唯一、两个密码一致
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password1 = form.cleaned_data["password1"]
            password2 = form.cleaned_data["password2"]
            # 　方法一：
            # user = User.objects.filter(username=username)
            # if password1 == password2 and not user:
            #     user = User.objects.create_user(username, email, password1)
            #     user.save()
            #     _login(request, username, password1)
            #     # 注册完毕 直接登陆
            #     return redirect(reverse("forms_auth:index"))

            # 方法二、利用Form的clean进行验证
            user  = User.objects.create_user(username,email,password1)
            user.save()

            #注册完毕，直接登录
            _login(request,username,password1)

            return redirect(reverse("forms_auth:index"))
    return render(request, "forms_auth/register.html", {"form":form})

def logout(request):
    auth_logout(request)
    return redirect(reverse('forms_auth:login'))

djangostart/apps/forms_auth/templates/forms_auth/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户首页</title>
</head>
<body>
欢迎你,{{ request.user }}
欢迎你,{{ request.user.email }}

<p>
    <a href="{% url 'forms_auth:login' %}">登陆</a>
    <a href="{% url 'forms_auth:register' %}">注册</a>
    <a href="{% url 'forms_auth:logout' %}">注销</a>
    <a href="{% url 'forms_auth:index' %}">返回首页</a>
</p>
</body>
</html>

djangostart/apps/forms_auth/templates/forms_auth/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户登录</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form method="post">
    {#  CSRF跨域请求伪造 #}
    {# 如果使用post方式,启用了csrf中间件,请记得添加{% csrf_token %} #}
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="登录">
</form>
<p>
    <a href="{% url 'forms_auth:login' %}">登陆</a>
    <a href="{% url 'forms_auth:register' %}">注册</a>
    <a href="{% url 'forms_auth:logout' %}">注销</a>
    <a href="{% url 'forms_auth:index' %}">返回首页</a>
</p>

</body>
</html>

djangostart/apps/forms_auth/templates/forms_auth/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
</head>
<body>
<form method="post">
    {#  CSRF跨域请求伪造 #}
    {# 如果使用post方式,启用了csrf中间件,请记得添加{% csrf_token %} #}
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="注册">
</form>
<p>
    <a href="{% url 'forms_auth:login' %}">登陆</a>
    <a href="{% url 'forms_auth:register' %}">注册</a>
    <a href="{% url 'forms_auth:logout' %}">注销</a>
    <a href="{% url 'forms_auth:index' %}">返回首页</a>
</p>

</body>
</html>